### ISSUE TITLE
npm ERR! missing script: start

### ISSUE THREAD

**Issue by itshazlan** [sivadass/react-meeting-room#1]
Hi, I'm very newly to React Native and try to test your project, but it give me error like this
npm ERR! missing script: start

I hope you find the solution, thank you!

**Comment by polargeex** [comment]
It's problem with start script of package.json.

I don't find the good option, please can you help us and say us more about your developement environement?

**Comment by sivadass** [comment]
Hi @hamzahalvanaa  and @polargeex , sorry I missed this issue un-noticed.

Now I have added the start script:

`npm start` and `npm run build` are available now.

**Comment by polargeex** [comment]
it's a shame, I stayed all night and it works for me with my fix. It was a bit hard to discovery react and node js ;-)

I will test your last version as soon as possible.

Thank you very much!
