### ISSUE TITLE
gapi.load doesnt work

### ISSUE THREAD

**Issue by rahilahmad** [sivadass/react-meeting-room#2]
i am trying to use your code in my app and there is an error occurs that gapi.load undefined can you help me to solve this issue

**Comment by sivadass** [comment]
Can you please show me your code or console logs to help you further?

**Comment by Raheel1258** [comment]
My code is in office laptop.basically my app is on redux i just copy and paste your code to check i install all the dependicies on create-react-app but there is an error that gapi.load is undefined.when i run your code by cloning it runs correctly...i will show you the code kindly give me your email.

**Comment by sivadass** [comment]
You can find my email from my profile [here](https://github.com/sivadass).

**Comment by rahilahmad** [comment]
Thanks my issue has been resolved

**Comment by sivadass** [comment]
Thanks @rahilahmad .
